### ISSUE TITLE
How to create export this design to Xilinx SDK

### ISSUE THREAD

**Issue by ntutangyun** [suoto/grlib#1]
Hi, i wish to work on the software application with XilinX SDK, but i cannot export the hardware since there is no block design. 

I'm new to this field, i wonder how to create a block design from it and eventually export to XilinX SDK

Thank You

**Comment by suoto** [comment]
This is just a personal mirror, for info on the Leon3 check out https://www.gaisler.com/index.php/downloads/leongrlib.
